version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: vanzep/foodgram_backend
    env_file: .env
    volumes:
      - static:/static
      - media:/media

  frontend:
    image: vanzep/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  nginx:
    image: vanzep/foodgram_nginx
    env_file: .env
    ports:
      - 7000:80
    volumes:
      - static:/static
      - media:/media
      - ./docs/:/usr/share/nginx/html/api/docs/
